# Generated by Django 3.0.4 on 2020-04-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillsAgreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rate', models.FloatField()),
                ('is_dynamic', models.BooleanField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_agreement', to='flat.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='BillsHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate', models.FloatField()),
                ('value', models.IntegerField(blank=True, null=True)),
                ('difference', models.IntegerField(blank=True, null=True)),
                ('total', models.IntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.BillsAgreement')),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_history', to='flat.Flat')),
            ],
        ),
    ]
