# Generated by Django 3.0.4 on 2020-04-02 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills_agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('is_dynamic', models.BooleanField()),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills_agreement', to='flat.Flat')),
            ],
        ),
    ]
