# Generated by Django 3.0.4 on 2020-04-02 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills_agreement',
            name='rate',
            field=models.FloatField(),
        ),
    ]
