# Generated by Django 3.0.4 on 2020-04-03 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20200403_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billshistory',
            name='total',
            field=models.FloatField(),
        ),
    ]
