# Generated by Django 3.0.4 on 2020-03-27 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=60)),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='user.User')),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('flat_id', models.IntegerField()),
                ('tenant_id', models.IntegerField()),
                ('bills', models.IntegerField()),
                ('rental_rate', models.IntegerField()),
                ('total', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signingDate', models.DateField()),
                ('paymentDay', models.IntegerField()),
                ('contractTime', models.IntegerField()),
                ('rental_rate', models.IntegerField()),
                ('deposit', models.IntegerField()),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flat', to='flat.Flat', unique=True)),
                ('tenant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.User', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bills_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('value', models.IntegerField()),
                ('difference', models.IntegerField()),
                ('total', models.IntegerField()),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='Bills_agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('rate', models.IntegerField()),
                ('is_dynamic', models.BooleanField()),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flat.Flat')),
            ],
        ),
    ]
