# Generated by Django 3.0.4 on 2020-04-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='flat',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='flat.Flat'),
        ),
    ]
